name: save_children_v01
description: A new Flutter project.

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  dropdown_button2: 2.0.0
  file_picker: 5.2.6
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_plugin_android_lifecycle: 2.0.9
  flutter_rating_bar: 4.0.1
  flutter_spinkit: 5.1.0
  flutter_staggered_grid_view: 0.6.2
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  image_picker: ^0.8.7+5
  image_picker_android: 0.8.5+3
  image_picker_for_web: 2.1.10
  image_picker_ios: 0.8.6+1
  image_picker_platform_interface: 2.6.2
  intl: 0.18.0
  json_path: 0.4.1
  mime_type: 1.0.0
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  plugin_platform_interface: 2.1.3
  provider: 6.0.4
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  video_player: 2.6.0
  video_player_android: 2.4.3
  video_player_avfoundation: 2.4.2
  video_player_platform_interface: 6.1.0
  video_player_web: 2.0.15
  dio: ^4.0.6
  http: ^0.13.6
  http_parser: ^4.0.2
  fluttertoast: ^8.2.2
  kakao_flutter_sdk_user: ^1.3.1
  firebase_core: ^1.10.0
  firebase_messaging: ^11.2.0
  firebase_core_platform_interface: 4.5.1





dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts: 
    - family: SUITE
      fonts:
        - asset: assets/fonts/SUITE-Variable.ttf
        - asset: assets/fonts/SUITE-Medium.ttf # 폰트가 이상한것 같아서 추가했습니다. 혹시 문제 없으시면 지우셔도 됩니다.
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf
    - family: lexend deca
      fonts:
        - asset: assets/fonts/LexendDeca-VariableFont_wght.ttf
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
  assets:
    - assets/images/
  